### ISSUE TITLE
Reliable segfaults in tests (I think the module does not work at all)

### ISSUE THREAD

**Issue by AlexDaniel** [zostay/DateTime-DST#4]
See the output on all rakudo releases:
https://gist.github.com/Whateverable/1786e70fbce5223fdb2c48cb05265ec6

So it's not a regression and my best guess is that the module is simply broken.

**Comment by zostay** [comment]
It sort of worked (compiled at least) on systems that have 32-bit time handling, but that's not the case on many systems anymore. I'm changing it now so that it will work regardless of whether `time_t` is 32-bit or 64-bit and regardless of what size of fields `struct tm` looks like on the host system, as such things are only vaguely defined by the relevant standards. I hadn't realized it at the time of first writing.

I also seem to have been in a hurry as there were several other typos in the tests an META6 that would have prevented it from installing and working correctly anyway. :(

I hope all of that will be fixed shortly. The compile issue, at least, is fixed.
